server:
  port: 8080

spring:
  application:
    name: bugtracker

  datasource:
    url: jdbc:postgresql://localhost:5432/bugtracker
    username: postgres
    password: shaikimran123!@#
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
